[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"

# Collection settings for production
COLLECTION_INTERVAL_HOURS = "4"
REQUEST_TIMEOUT_SECONDS = "30"
MAX_RETRIES = "3"
BACKOFF_FACTOR = "2"

# Rate limiting - conservative for production
REQUESTS_PER_MINUTE = "10"
MIN_REQUEST_INTERVAL_SECONDS = "6"

# Logging settings optimized for Railway
LOG_FILE_PATH = "/tmp/tecdata.log"
LOG_ROTATION = "1 day"
LOG_RETENTION = "7 days"

# API settings
TECMUNDO_API_BASE_URL = "https://www.tecmundo.com.br"
TECMUNDO_API_ENDPOINT = "/api/posts?endpoint=home-author"

[environments.production.services.web]
name = "tecdata-web"
type = "web"
source = "."
buildCommand = "pip install -r requirements.txt"
startCommand = "python app.py"
port = 8000

[environments.production.services.worker]
name = "tecdata-worker"
type = "worker"
source = "."
buildCommand = "pip install -r requirements.txt"
startCommand = "python worker.py"

[environments.production.services.database]
name = "tecdata-postgres"
type = "postgresql"
version = "15"