[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
COLLECTION_INTERVAL_HOURS = "4"